//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaFrba.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendum
    {
        public int agenda_id { get; set; }
        public int profesional_id { get; set; }
        public string agenda_dia { get; set; }
        public System.TimeSpan agenda_hora_desde { get; set; }
        public System.TimeSpan agenda_hora_hasta { get; set; }
        public System.DateTime agenda_fecha_desde { get; set; }
        public System.DateTime agenda_fecha_hasta { get; set; }
        public int especialidad_id { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual Profesional Profesional { get; set; }
    }
}
