//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaFrba.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaMedica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsultaMedica()
        {
            this.Diagnosticoes = new HashSet<Diagnostico>();
            this.Sintomas = new HashSet<Sintoma>();
        }
    
        public int consultamedica_id { get; set; }
        public int bono_id { get; set; }
        public Nullable<System.DateTime> consultamedica_fecha_hora { get; set; }
        public Nullable<bool> consultamedica_ocurrio { get; set; }
    
        public virtual Bono Bono { get; set; }
        public virtual Turno Turno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnostico> Diagnosticoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sintoma> Sintomas { get; set; }
    }
}
