//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaFrba.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostico
    {
        public int diagnostico_id { get; set; }
        public int consultamedica_id { get; set; }
        public string diagnostico_descripcion { get; set; }
    
        public virtual ConsultaMedica ConsultaMedica { get; set; }
    }
}
