//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaFrba.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialPlan
    {
        public int afiliado_id { get; set; }
        public System.DateTime historial_fecha { get; set; }
        public string historial_motivo { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
    }
}
