//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaFrba.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaAfiliado
    {
        public int usuario_id { get; set; }
        public int afiliado_numero { get; set; }
        public string afiliado_nombre { get; set; }
        public string afiliado_apellido { get; set; }
    }
}
