//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaFrba.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int plan_id { get; set; }
        public string plan_nombre { get; set; }
        public decimal plan_cuota { get; set; }
        public decimal plan_precio_bono { get; set; }
    }
}
