//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaFrba.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesional()
        {
            this.Agenda = new HashSet<Agendum>();
            this.Turnoes = new HashSet<Turno>();
            this.Especialidads = new HashSet<Especialidad>();
        }
    
        public int profesional_id { get; set; }
        public int usuario_id { get; set; }
        public int sexo_id { get; set; }
        public int tipodocumento_id { get; set; }
        public int profesional_numero_documento { get; set; }
        public string profesional_nombre { get; set; }
        public string profesional_apellido { get; set; }
        public string profesional_direccion { get; set; }
        public int profesional_telefono { get; set; }
        public string profesional_mail { get; set; }
        public System.DateTime profesional_fecha_nacimiento { get; set; }
        public int profesional_matricula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendum> Agenda { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turno> Turnoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Especialidad> Especialidads { get; set; }

        public override string ToString()
        {
            return profesional_nombre.Trim() + " " + profesional_apellido.Trim(); 
        }
    }
}
