//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaFrba.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCancelacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoCancelacion()
        {
            this.TurnoCanceladoes = new HashSet<TurnoCancelado>();
        }
    
        public int tipocancelacion_id { get; set; }
        public string tipocancelacion_nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurnoCancelado> TurnoCanceladoes { get; set; }
        public override string ToString()
        {
            return tipocancelacion_nombre.Trim();
        }
    }
}
