//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaFrba.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int turno_id { get; set; }
        public int afiliado_id { get; set; }
        public int profesional_id { get; set; }
        public Nullable<int> bono_id { get; set; }
        public int especialidad_id { get; set; }
        public System.DateTime turno_fecha_hora { get; set; }
        public string turno_cancelado { get; set; }
        public string turno_diagnostico { get; set; }
        public string turno_sintomas { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
        public virtual Bono Bono { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        public virtual Profesional Profesional { get; set; }
    }
}
