//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaFrba.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turno()
        {
            this.Diagnosticoes = new HashSet<Diagnostico>();
        }
    
        public int turno_id { get; set; }
        public int afiliado_id { get; set; }
        public int profesional_id { get; set; }
        public Nullable<int> bono_id { get; set; }
        public Nullable<System.DateTime> turno_fecha_hora { get; set; }
        public string turno_cancelado { get; set; }
        public int especialidad_id { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
        public virtual Bono Bono { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        public virtual Profesional Profesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnostico> Diagnosticoes { get; set; }
    }
}
