//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaFrba.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ListarEsp
    {
        public int especialidad_id { get; set; }
        public string especialidad_nombre { get; set; }
        public int tipoespecialidad_id { get; set; }
        public string tipoespecialidad_nombre { get; set; }
    }
}
